/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef } from 'react';
import { formatCLP, formatPercent } from '../utils';
import { 
  DollarSign, Percent, TrendingUp, Sparkles, Scale, Info, 
  ArrowUpRight, Award, Database, Download, Upload, Trash2, Check, RefreshCw
} from 'lucide-react';
import { StockHolding } from '../types';

interface ChartsAndAnalyticsProps {
  holdings?: StockHolding[];
  contributedCapital: number;
  totalDividends: number;
  totalTaxRefunds: number;
  annualPerformancePercentage: number;
  setAnnualPerformancePercentage: (val: number) => void;
  holdingsCount: number;
  onExportBackup: () => void;
  onImportBackup: (content: string) => Promise<void>;
  onClearAllData: () => Promise<void>;
}

export default function ChartsAndAnalytics({
  holdings = [],
  contributedCapital,
  totalDividends,
  totalTaxRefunds,
  annualPerformancePercentage,
  setAnnualPerformancePercentage,
  holdingsCount,
  onExportBackup,
  onImportBackup,
  onClearAllData
}: ChartsAndAnalyticsProps) {
  const [projectionYear, setProjectionYear] = useState<number>(5);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [importStatus, setImportStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [importError, setImportError] = useState('');
  const [showClearConfirm, setShowClearConfirm] = useState(false);

  // --- CALCULATIONS FOR PAPER PROFIT AND LOSS ---
  const listHoldings = holdings || [];
  
  // Total capital invertido según la suma de costo de compra de cada holding
  const computedContributed = listHoldings.reduce((sum, h) => sum + (h.shares * h.buyPrice), 0);
  // Valorización actual según precio del mercado
  const computedCurrentValue = listHoldings.reduce((sum, h) => sum + (h.shares * h.currentPrice), 0);
  
  // Pérdidas No Realizadas (Minusvalías en acciones que bajaron de precio)
  const totalLosses = listHoldings.reduce((sum, h) => {
    const diff = h.currentPrice - h.buyPrice;
    if (diff < 0) {
      return sum + (Math.abs(diff) * h.shares);
    }
    return sum;
  }, 0);

  // Ganancias de Capital No Realizadas (Plusvalías en acciones que subieron de precio)
  const totalGains = listHoldings.reduce((sum, h) => {
    const diff = h.currentPrice - h.buyPrice;
    if (diff > 0) {
      return sum + (diff * h.shares);
    }
    return sum;
  }, 0);

  // Rendimiento neto de valorización del portafolio (Plusvalías - Minusvalías)
  const netCapitalGainOrLoss = computedCurrentValue - computedContributed;
  const isNetGain = netCapitalGainOrLoss >= 0;

  const holdingsWithLosses = listHoldings.filter(h => h.currentPrice < h.buyPrice);
  const holdingsWithGains = listHoldings.filter(h => h.currentPrice > h.buyPrice);

  const totalFunds = contributedCapital + totalDividends + totalTaxRefunds;

  // Split contributed capital into preserved capital and lost capital
  const capitalConservado = Math.max(0, contributedCapital - totalLosses);

  const pctCapitalConservado = totalFunds > 0 ? (capitalConservado / totalFunds) * 100 : 100;
  const pctLosses = totalFunds > 0 ? (totalLosses / totalFunds) * 100 : 0;
  const pctDividends = totalFunds > 0 ? (totalDividends / totalFunds) * 100 : 0;
  const pctTaxes = totalFunds > 0 ? (totalTaxRefunds / totalFunds) * 100 : 0;

  // Actual annual yield generated by dividends + tax refunds compared to contributed capital
  const generatedYieldPercent = contributedCapital > 0 
    ? ((totalDividends + totalTaxRefunds) / contributedCapital) * 100 
    : 0;

  // Let's compute compounding projection based on the user-defined annual percentage yield
  const compPercentage = annualPerformancePercentage / 100;
  const projectedValue = contributedCapital * Math.pow(1 + compPercentage, projectionYear);
  const projectedEarned = projectedValue - contributedCapital;

  // Interactive tooltip state for Donut Chart
  const [activeSegment, setActiveSegment] = useState<string | null>(null);

  // SVG parameters for Donut Chart
  const radius = 50;
  const strokeWidth = 14;
  const circumference = 2 * Math.PI * radius; // ~314.16

  // Calculate Dash Offsets for the four slices in a continuous donut
  const dashOffset1 = 0;
  const strokeLength1 = (circumference * pctCapitalConservado) / 100;

  const strokeLengthLosses = (circumference * pctLosses) / 100;
  const dashOffsetLosses = circumference - strokeLength1;

  const strokeLength2 = (circumference * pctDividends) / 100;
  const dashOffset2 = circumference - strokeLength1 - strokeLengthLosses;

  const strokeLength3 = (circumference * pctTaxes) / 100;
  const dashOffset3 = circumference - strokeLength1 - strokeLengthLosses - strokeLength2;

  // Maximum value for Bar Chart scaling
  const maxBarValue = Math.max(contributedCapital, totalDividends, totalTaxRefunds, totalLosses, totalGains, 1000);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (event) => {
      try {
        const text = event.target?.result as string;
        // Verify JSON parseable
        JSON.parse(text);
        await onImportBackup(text);
        setImportStatus('success');
        setTimeout(() => setImportStatus('idle'), 4000);
      } catch (err: any) {
        setImportStatus('error');
        setImportError(err?.message || 'Archivo de respaldo dañado o incorrecto.');
        setTimeout(() => setImportStatus('idle'), 4000);
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  const handleClearClick = async () => {
    if (!showClearConfirm) {
      setShowClearConfirm(true);
      return;
    }
    await onClearAllData();
    setShowClearConfirm(false);
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Metric Overview Widget */}
        <div className="lg:col-span-1 bg-white p-6 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center space-x-2 text-indigo-600">
              <Award className="w-5 h-5" />
              <h3 className="font-bold text-slate-800 text-sm">Resumen de Rentabilidad</h3>
            </div>
            
            <div className="space-y-2 pt-2">
              <span className="text-xs text-slate-400 block">Tasa de Dividendos + Devolución Generada</span>
              <span className="text-3xl font-extrabold font-mono text-emerald-600 block">
                {generatedYieldPercent.toFixed(2)}%
              </span>
              <p className="text-[11px] text-slate-500 leading-relaxed">
                Rentabilidad pasiva total acumulada en base al capital aportado. Esto incluye dividendos cobrados y créditos fiscales devueltos de la Operación Renta.
              </p>
            </div>

            {/* Rendimiento sobre Precio (Papel) (Minusvalías / Plusvalías) */}
            <div className="pt-3 border-t border-slate-100 flex flex-col gap-2.5">
              <span className="text-xs font-bold text-slate-700 block">Rendimiento sobre Precio (Papel)</span>
              
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div className="p-2.5 bg-rose-50 border border-rose-100/50 rounded-lg">
                  <span className="text-[10px] text-rose-500 uppercase font-bold tracking-wider block">Minusvalía Total</span>
                  <span className="font-bold text-rose-700 font-mono text-xs">-{formatCLP(totalLosses)}</span>
                  <span className="text-[10px] text-rose-400 block font-medium font-mono">
                    {holdingsWithLosses.length} {holdingsWithLosses.length === 1 ? 'activa' : 'activas'}
                  </span>
                </div>
                
                <div className="p-2.5 bg-emerald-50 border border-emerald-100/50 rounded-lg">
                  <span className="text-[10px] text-emerald-500 uppercase font-bold tracking-wider block">Plusvalía Total</span>
                  <span className="font-bold text-emerald-700 font-mono text-xs">+{formatCLP(totalGains)}</span>
                  <span className="text-[10px] text-emerald-400 block font-medium font-mono">
                    {holdingsWithGains.length} {holdingsWithGains.length === 1 ? 'activa' : 'activas'}
                  </span>
                </div>
              </div>

              {listHoldings.length > 0 && (
                <div className={`text-[10px] uppercase font-bold px-2 py-1 rounded text-center font-mono ${isNetGain ? 'bg-emerald-50 text-emerald-800 border border-emerald-100/40' : 'bg-rose-50 text-rose-800 border border-rose-100/40'}`}>
                  Balance Neto: {isNetGain ? '+' : ''}{formatCLP(netCapitalGainOrLoss)} ({((netCapitalGainOrLoss / (computedContributed || 1)) * 100).toFixed(2)}%)
                </div>
              )}
            </div>

            {/* Input to place/configure annual percentage generated */}
            <div className="pt-4 border-t border-slate-100 space-y-2">
              <div className="flex justify-between items-center">
                <label className="text-xs font-semibold text-slate-700 flex items-center gap-1">
                  <Percent className="w-3.5 h-3.5 text-indigo-500" />
                  Rentabilidad Objetivo Anual (%)
                </label>
                <span className="text-xs font-mono font-bold text-indigo-600">{annualPerformancePercentage}% anual</span>
              </div>
              <input
                type="range"
                min="0"
                max="30"
                step="0.1"
                value={annualPerformancePercentage}
                onChange={(e) => setAnnualPerformancePercentage(Number(e.target.value))}
                className="w-full accent-indigo-600 h-1.5 bg-slate-100 rounded-lg appearance-none cursor-pointer"
              />
              <div className="flex justify-between text-[10px] text-slate-400 font-mono">
                <span>0% min</span>
                <span>IPSA Histórico (8-11%)</span>
                <span>30% máx</span>
              </div>
            </div>
          </div>

          {/* Integrated Compounding & Capitalization Simulator */}
          <div className="pt-4 mt-4 border-t border-slate-100 space-y-3">
            <div className="bg-indigo-950 text-white rounded-xl p-3.5 border border-indigo-900 shadow-sm relative overflow-hidden">
              <div className="absolute right-0 top-0 transform translate-x-6 -translate-y-6 text-indigo-900 opacity-20 pointer-events-none">
                <TrendingUp className="w-24 h-24" />
              </div>
              
              <div className="relative z-10 space-y-2.5">
                <div className="flex items-center space-x-1.5">
                  <Sparkles className="w-3.5 h-3.5 text-teal-300" />
                  <span className="text-[10px] font-bold text-teal-300 uppercase tracking-wider">Simulación de Interés Compuesto</span>
                </div>
                
                <div className="space-y-1">
                  <div className="flex justify-between text-[11px] text-indigo-100 font-medium">
                    <span>Horizonte:</span>
                    <span className="font-extrabold text-white font-mono">{projectionYear} Años</span>
                  </div>
                  <input
                    type="range"
                    min="1"
                    max="30"
                    step="1"
                    value={projectionYear}
                    onChange={(e) => setProjectionYear(Number(e.target.value))}
                    className="w-full h-1 bg-indigo-900 rounded-lg appearance-none cursor-pointer accent-teal-400"
                  />
                </div>

                <div className="grid grid-cols-2 gap-2 pt-1.5 border-t border-indigo-900">
                  <div className="space-y-0.5">
                    <span className="text-[9px] uppercase tracking-wider text-indigo-200 block">Ganancia Proyectada</span>
                    <span className="text-xs font-bold font-mono text-emerald-400">+{formatCLP(projectedEarned)}</span>
                  </div>
                  <div className="space-y-0.5">
                    <span className="text-[9px] uppercase tracking-wider text-indigo-200 block">Valor Estimado</span>
                    <span className="text-xs font-bold font-mono text-white">{formatCLP(projectedValue)}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Combined Charts: Donut & Bar Chart (Distribución & Comparativa) */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-between space-y-4">
          {/* 1. Donut Chart (Gráfico Redondo) Section */}
          <div className="space-y-3">
            <div className="border-b border-slate-100 pb-2">
              <h3 className="font-bold text-slate-800 text-sm flex items-center justify-between">
                <span>Distribución del Capital Activo</span>
                {activeSegment && (
                  <span className="text-[9px] bg-slate-900 text-white font-mono px-1.5 py-0.5 rounded uppercase font-semibold">
                    {activeSegment}
                  </span>
                )}
              </h3>
              <p className="text-[11px] text-slate-400">Capital invertido frente a dividendos e impuestos devueltos</p>
            </div>

            <div className="flex flex-col items-center justify-center gap-4 mt-1">
              {/* SVG Donut */}
              <div className="relative w-36 h-36 shrink-0">
                <svg className="w-full h-full transform -rotate-90" viewBox="0 0 120 120">
                  {/* Background Ring */}
                  <circle
                    cx="60"
                    cy="60"
                    r={radius}
                    fill="transparent"
                    stroke="#f1f5f9"
                    strokeWidth={strokeWidth}
                  />
                  
                  {/* Segment 1: Capital Activo Conservado */}
                  <circle
                    cx="60"
                    cy="60"
                    r={radius}
                    fill="transparent"
                    stroke="#334155"
                    strokeWidth={strokeWidth}
                    strokeDasharray={`${strokeLength1} ${circumference - strokeLength1}`}
                    strokeDashoffset={dashOffset1}
                    strokeLinecap="round"
                    className="transition-all duration-500 cursor-pointer hover:stroke-[16px]"
                    onMouseEnter={() => setActiveSegment(`Conservado (${pctCapitalConservado.toFixed(1)}%)`)}
                    onMouseLeave={() => setActiveSegment(null)}
                  />

                  {/* Segment 2: Minusvalías */}
                  {pctLosses > 0 && (
                    <circle
                      cx="60"
                      cy="60"
                      r={radius}
                      fill="transparent"
                      stroke="#f43f5e"
                      strokeWidth={strokeWidth}
                      strokeDasharray={`${strokeLengthLosses} ${circumference - strokeLengthLosses}`}
                      strokeDashoffset={dashOffsetLosses}
                      strokeLinecap="round"
                      className="transition-all duration-500 cursor-pointer hover:stroke-[16px]"
                      onMouseEnter={() => setActiveSegment(`Minusvalía (${pctLosses.toFixed(1)}%)`)}
                      onMouseLeave={() => setActiveSegment(null)}
                    />
                  )}

                  {/* Segment 3: Dividends */}
                  {pctDividends > 0 && (
                    <circle
                      cx="60"
                      cy="60"
                      r={radius}
                      fill="transparent"
                      stroke="#14b8a6"
                      strokeWidth={strokeWidth}
                      strokeDasharray={`${strokeLength2} ${circumference - strokeLength2}`}
                      strokeDashoffset={dashOffset2}
                      strokeLinecap="round"
                      className="transition-all duration-500 cursor-pointer hover:stroke-[16px]"
                      onMouseEnter={() => setActiveSegment(`Dividendos (${pctDividends.toFixed(1)}%)`)}
                      onMouseLeave={() => setActiveSegment(null)}
                    />
                  )}

                  {/* Segment 4: Tax Refunds */}
                  {pctTaxes > 0 && (
                    <circle
                      cx="60"
                      cy="60"
                      r={radius}
                      fill="transparent"
                      stroke="#6366f1"
                      strokeWidth={strokeWidth}
                      strokeDasharray={`${strokeLength3} ${circumference - strokeLength3}`}
                      strokeDashoffset={dashOffset3}
                      strokeLinecap="round"
                      className="transition-all duration-500 cursor-pointer hover:stroke-[16px]"
                      onMouseEnter={() => setActiveSegment(`Impuestos (${pctTaxes.toFixed(1)}%)`)}
                      onMouseLeave={() => setActiveSegment(null)}
                    />
                  )}
                </svg>

                {/* Center value */}
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                  <div className="text-[8px] uppercase font-mono tracking-wider text-slate-400 font-bold mb-0.5">Total</div>
                  <div className="text-[11px] font-black text-slate-900 font-mono leading-none">{formatCLP(totalFunds)}</div>
                </div>
              </div>

              {/* Legends (ordered vertically, beautifully spaced out and larger to balance heights) */}
              <div className="flex flex-col gap-2 w-full pt-3 border-t border-slate-100">
                <div className="flex items-center justify-between py-1.5 border-b border-dashed border-slate-100 last:border-0 last:pb-0">
                  <div className="flex items-center space-x-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-slate-700 block shrink-0" />
                    <span className="font-semibold text-slate-700 text-xs">Cap. Conservado</span>
                  </div>
                  <div className="font-mono text-slate-800 text-xs text-right">
                    <span className="font-bold">{formatCLP(capitalConservado)}</span>
                    <span className="text-slate-400 text-[10px] ml-1.5">({pctCapitalConservado.toFixed(1)}%)</span>
                  </div>
                </div>

                {totalLosses > 0 && (
                  <div className="flex items-center justify-between py-1.5 border-b border-dashed border-slate-100 last:border-0 last:pb-0">
                    <div className="flex items-center space-x-2">
                      <span className="w-2.5 h-2.5 rounded-full bg-rose-500 block shrink-0" />
                      <span className="font-semibold text-slate-700 text-xs">Minusvalías</span>
                    </div>
                    <div className="font-mono text-rose-600 text-xs text-right">
                      <span className="font-bold">-{formatCLP(totalLosses)}</span>
                      <span className="text-rose-400 text-[10px] ml-1.5">({pctLosses.toFixed(1)}%)</span>
                    </div>
                  </div>
                )}

                <div className="flex items-center justify-between py-1.5 border-b border-dashed border-slate-100 last:border-0 last:pb-0">
                  <div className="flex items-center space-x-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-teal-500 block shrink-0" />
                    <span className="font-semibold text-slate-700 text-xs">Dividendos</span>
                  </div>
                  <div className="font-mono text-emerald-700 text-xs text-right">
                    <span className="font-bold">{formatCLP(totalDividends)}</span>
                    <span className="text-emerald-400 text-[10px] ml-1.5">({pctDividends.toFixed(1)}%)</span>
                  </div>
                </div>

                <div className="flex items-center justify-between py-1.5 border-b border-dashed border-slate-100 last:border-0 last:pb-0">
                  <div className="flex items-center space-x-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-indigo-500 block shrink-0" />
                    <span className="font-semibold text-slate-700 text-xs">Impuestos TGR</span>
                  </div>
                  <div className="font-mono text-indigo-700 text-xs text-right">
                    <span className="font-bold">{formatCLP(totalTaxRefunds)}</span>
                    <span className="text-indigo-400 text-[10px] ml-1.5">({pctTaxes.toFixed(1)}%)</span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* 2. Bar Chart (Gráfico de Barra) Section */}
          <div className="border-t border-slate-100 pt-3 space-y-2">
            <div>
              <h4 className="font-bold text-slate-800 text-xs">Comparativa de Fondos Adquiridos</h4>
              <p className="text-[10px] text-slate-400">Valores consolidados en CLP</p>
            </div>

            <div className="space-y-1.5">
              {/* Bar 1: Aportado */}
              <div>
                <div className="flex justify-between text-[10px] font-medium text-slate-700 mb-0.5">
                  <span>Capital Neto</span>
                  <span className="font-mono font-bold text-slate-900">{formatCLP(contributedCapital)}</span>
                </div>
                <div className="w-full bg-slate-100 rounded-full h-1 overflow-hidden">
                  <div 
                    className="bg-slate-700 h-full rounded-full transition-all duration-700 ease-out"
                    style={{ width: `${Math.max((contributedCapital / maxBarValue) * 100, 3)}%` }}
                  />
                </div>
              </div>

              {/* Bar 2: Dividendos */}
              <div>
                <div className="flex justify-between text-[10px] font-medium text-teal-800 mb-0.5">
                  <span>Dividendos</span>
                  <span className="font-mono font-bold text-teal-600">{formatCLP(totalDividends)}</span>
                </div>
                <div className="w-full bg-slate-100 rounded-full h-1 overflow-hidden">
                  <div 
                    className="bg-teal-500 h-full rounded-full transition-all duration-700 ease-out"
                    style={{ width: `${Math.max((totalDividends / maxBarValue) * 105, totalDividends > 0 ? 3 : 0)}%` }}
                  />
                </div>
              </div>

              {/* Bar 3: Impuestos */}
              <div>
                <div className="flex justify-between text-[10px] font-medium text-indigo-800 mb-0.5">
                  <span>Impuestos TGR</span>
                  <span className="font-mono font-bold text-indigo-600">{formatCLP(totalTaxRefunds)}</span>
                </div>
                <div className="w-full bg-slate-100 rounded-full h-1 overflow-hidden">
                  <div 
                    className="bg-indigo-500 h-full rounded-full transition-all duration-700 ease-out"
                    style={{ width: `${Math.max((totalTaxRefunds / maxBarValue) * 100, totalTaxRefunds > 0 ? 3 : 0)}%` }}
                  />
                </div>
              </div>

              {/* Bar 4: Plusvalías */}
              {totalGains > 0 && (
                <div>
                  <div className="flex justify-between text-[10px] font-medium text-emerald-800 mb-0.5">
                    <span>Plusvalía</span>
                    <span className="font-mono font-bold text-emerald-600">+{formatCLP(totalGains)}</span>
                  </div>
                  <div className="w-full bg-slate-100 rounded-full h-1 overflow-hidden">
                    <div 
                      className="bg-emerald-500 h-full rounded-full transition-all duration-700 ease-out"
                      style={{ width: `${Math.max((totalGains / maxBarValue) * 100, 3)}%` }}
                    />
                  </div>
                </div>
              )}

              {/* Bar 5: Minusvalías */}
              {totalLosses > 0 && (
                <div>
                  <div className="flex justify-between text-[10px] font-medium text-rose-800 mb-0.5">
                    <span>Minusvalía</span>
                    <span className="font-mono font-bold text-rose-600">-{formatCLP(totalLosses)}</span>
                  </div>
                  <div className="w-full bg-slate-100 rounded-full h-1 overflow-hidden">
                    <div 
                      className="bg-rose-500 h-full rounded-full transition-all duration-700 ease-out"
                      style={{ width: `${Math.max((totalLosses / maxBarValue) * 100, 3)}%` }}
                    />
                  </div>
                </div>
              )}
            </div>

            <div className="text-[9px] text-slate-400 leading-tight bg-slate-50 p-1.5 rounded border border-slate-100">
              📊 La barra superior representa la base imponible y las inferiores reflejan las ganancias o pérdidas del portafolio.
            </div>
          </div>
        </div>

        {/* Column 3: Local IndexedDB database & backup */}
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-xs flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between border-b border-slate-100 pb-2">
              <div className="flex items-center space-x-1.5">
                <Database className="w-4 h-4 text-slate-700" />
                <h3 className="font-bold text-slate-800 text-sm">Base de Datos Local (IndexedDB) & Respaldo</h3>
              </div>
              <span className="text-[10px] bg-slate-100 text-slate-600 font-mono px-1.5 py-0.5 rounded font-bold">
                IndexedDB
              </span>
            </div>
            <p className="text-[11px] text-slate-400 mt-2 leading-relaxed">
              Tus datos nunca salen de tu navegador. Disfruta de total privacidad y mantén copias de seguridad.
            </p>
          </div>

          <div className="space-y-2.5 pt-1">
            {/* Box 1: Export */}
            <div className="bg-slate-50/70 p-2.5 rounded-lg border border-slate-100 flex flex-col justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-800 block uppercase tracking-wider">Exportar Respaldo</span>
                <p className="text-[9px] text-slate-400 mt-0.5 leading-normal">
                  Descarga tus acciones, dividendos e impuestos en un archivo JSON local.
                </p>
              </div>
              <button
                onClick={onExportBackup}
                className="mt-2.5 flex items-center justify-center space-x-1.5 w-full bg-slate-900 text-white font-medium hover:bg-slate-800 text-[10px] py-2 rounded-md transition cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Guardar Respaldo (.json)</span>
              </button>
            </div>

            {/* Box 2: Import */}
            <div className="bg-slate-50/70 p-2.5 rounded-lg border border-slate-100 flex flex-col justify-between">
              <div>
                <span className="text-[10px] font-bold text-slate-800 block uppercase tracking-wider">Restaurar Respaldo</span>
                <p className="text-[9px] text-slate-400 mt-0.5 leading-normal">
                  Sube tu archivo para recuperar de manera inmediata tu portafolio.
                </p>
              </div>
              <div className="mt-2.5">
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handleFileChange}
                  accept=".json"
                  className="hidden"
                />
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="flex items-center justify-center space-x-1.5 w-full bg-white text-slate-800 border border-slate-200 font-semibold hover:bg-slate-50 text-[10px] py-2 rounded-md transition cursor-pointer"
                >
                  <Upload className="w-3.5 h-3.5 text-slate-500" />
                  <span>Cargar Archivo Respaldo</span>
                </button>
                
                {importStatus === 'success' && (
                  <div className="mt-1.5 text-[9px] text-emerald-600 font-medium flex items-center gap-1 bg-emerald-50 p-1 rounded">
                    <Check className="w-3 h-3" /> ¡Respaldo importado con éxito!
                  </div>
                )}
                {importStatus === 'error' && (
                  <div className="mt-1.5 text-[9px] text-rose-600 font-medium bg-rose-50 p-1 rounded leading-normal">
                    ⚠ Error: {importError}
                  </div>
                )}
              </div>
            </div>

            {/* Box 3: Reset */}
            <div className="bg-slate-50/70 p-2.5 rounded-lg border border-slate-100 flex flex-col justify-between">
              <div>
                <span className="text-[10px] font-bold text-rose-800 block uppercase tracking-wider">Reiniciar Aplicación</span>
                <p className="text-[9px] text-slate-400 mt-0.5 leading-normal">
                  Borra por completo tus acciones e historial. Esta acción es irreversible.
                </p>
              </div>
              <div className="mt-2.5">
                {showClearConfirm ? (
                  <div className="space-y-1">
                    <button
                      onClick={handleClearClick}
                      className="flex items-center justify-center space-x-1.5 w-full bg-rose-600 text-white font-medium hover:bg-rose-700 text-[10px] py-1.5 rounded-md transition cursor-pointer"
                    >
                      <Trash2 className="w-3 h-3" />
                      <span>Confirmar Borrado</span>
                    </button>
                    <button
                      onClick={() => setShowClearConfirm(false)}
                      className="text-center block text-[9px] text-slate-500 hover:underline w-full py-0.5 cursor-pointer"
                    >
                      Cancelar
                    </button>
                  </div>
                ) : (
                  <button
                    onClick={handleClearClick}
                    className="flex items-center justify-center space-x-1.5 w-full bg-rose-50 text-rose-700 border border-rose-200 font-medium hover:bg-rose-100 text-[10px] py-2 rounded-md transition cursor-pointer"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    <span>Vaciar Datos</span>
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
